blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/jaylane/vscode-llms-txt/discussions
    about: Please ask and answer questions here.
  - name: Feature Request
    url: https://github.com/jaylane/vscode-llms-txt/discussions/categories/ideas
    about: Suggest ideas for new features.
  - name: Bug Report
    url: https://github.com/jaylane/vscode-llms-txt/issues/new?template=bug_report.md
    about: Report a reproducible bug.
